//
//  ProjectGenerator.swift
//  JobsPodBinaryBuilder
//
//  Created by Jobs on 2026年7月30日，星期四.
//

import Foundation

enum ProjectGenerator {
    // 生成用于 CocoaPods 集成和 Pod Target 构建的临时宿主工程。
    static func writePackagingWorkspace(
        at sessionURL: URL,
        rootSpec: PodSpecRecord,
        allSpecs: [PodSpecRecord]
    ) throws {
        try FileManager.default.createDirectory(
            at: sessionURL,
            withIntermediateDirectories: true
        )
        try writeHostProject(
            at: sessionURL,
            projectName: "PackagingHost",
            sourceFileName: "AppDelegate.swift",
            sourceContents: swiftHostSource,
            sourceFileType: "sourcecode.swift",
            deploymentTarget: "12.0"
        )
        let podfile = packagingPodfile(rootSpec: rootSpec, allSpecs: allSpecs)
        try podfile.write(
            to: sessionURL.appendingPathComponent("Podfile"),
            atomically: true,
            encoding: .utf8
        )
    }

    // 生成最终二进制产物的最小消费工程。
    static func writeConsumerDemo(
        at consumerURL: URL,
        rootSpec: PodSpecRecord,
        binarySDKURL: URL
    ) throws {
        try FileManager.default.createDirectory(
            at: consumerURL,
            withIntermediateDirectories: true
        )
        let source = """
        import UIKit
        import \(rootSpec.moduleName)

        @main
        final class AppDelegate: UIResponder, UIApplicationDelegate {
            var window: UIWindow?

            func application(
                _ application: UIApplication,
                didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]? = nil
            ) -> Bool {
                let window = UIWindow(frame: UIScreen.main.bounds)
                window.rootViewController = UIViewController()
                window.makeKeyAndVisible()
                self.window = window
                return true
            }
        }
        """
        try writeHostProject(
            at: consumerURL,
            projectName: "ConsumerDemo",
            sourceFileName: "AppDelegate.swift",
            sourceContents: source,
            sourceFileType: "sourcecode.swift",
            deploymentTarget: "12.0"
        )
        let relativePath = relativePath(from: consumerURL, to: binarySDKURL)
        let podfile = """
        platform :ios, '12.0'
        project 'ConsumerDemo.xcodeproj'
        use_frameworks! :linkage => :static

        target 'ConsumerDemo' do
          pod '\(rootSpec.name)', :path => '\(rubySingleQuoted(relativePath))'
        end
        """
        try podfile.write(
            to: consumerURL.appendingPathComponent("Podfile"),
            atomically: true,
            encoding: .utf8
        )
    }

    // 生成面向二进制 SDK 的本地 podspec。
    static func binaryPodspec(
        rootSpec: PodSpecRecord,
        dependencySpecs: [PodSpecRecord],
        frameworkRelativePaths: [String],
        hasResources: Bool
    ) -> String {
        let frameworks = frameworkRelativePaths
            .map { "    '\(rubySingleQuoted($0))'" }
            .joined(separator: ",\n")
        let systemFrameworks = Array(Set(
            ([rootSpec] + dependencySpecs).flatMap(\.frameworks)
        )).sorted()
        let systemLibraries = Array(Set(
            ([rootSpec] + dependencySpecs).flatMap(\.libraries)
        )).sorted()
        let frameworksBlock = systemFrameworks.isEmpty
            ? ""
            : "\n  spec.frameworks = \(rubyArray(systemFrameworks))"
        let librariesBlock = systemLibraries.isEmpty
            ? ""
            : "\n  spec.libraries = \(rubyArray(systemLibraries))"
        let resourcesBlock = hasResources
            ? "\n  spec.resources = 'Resources/**/*'"
            : ""

        return """
        Pod::Spec.new do |spec|
          spec.name             = '\(rubySingleQuoted(rootSpec.name))'
          spec.version          = '\(rubySingleQuoted(rootSpec.version))'
          spec.summary          = '\(rubySingleQuoted(rootSpec.summary.isEmpty ? "Binary distribution for \(rootSpec.name)." : rootSpec.summary))'
          spec.description      = 'Generated by JobsPodBinaryBuilder from a user-confirmed and locked dependency graph.'
          spec.homepage         = 'https://example.local/\(rubySingleQuoted(rootSpec.name))'
          spec.license          = { :type => '\(rubySingleQuoted(rootSpec.license))' }
          spec.author           = { 'Jobs' => 'lg295060456@gmail.com' }
          spec.platform         = :ios, '12.0'
          spec.source           = { :path => '.' }
          spec.module_name      = '\(rubySingleQuoted(rootSpec.moduleName))'
          spec.vendored_frameworks = [
        \(frameworks)
          ]\(frameworksBlock)\(librariesBlock)\(resourcesBlock)
        end
        """
    }

    // 生成打包宿主使用的 Podfile，强制所有本地 Pod 使用显式路径。
    private static func packagingPodfile(
        rootSpec: PodSpecRecord,
        allSpecs: [PodSpecRecord]
    ) -> String {
        let sortedSpecs = allSpecs.sorted {
            if $0.name == rootSpec.name { return true }
            if $1.name == rootSpec.name { return false }
            return $0.name < $1.name
        }
        let podLines = sortedSpecs.map { spec -> String in
            if spec.sourceKind.isLocal {
                return "  pod '\(rubySingleQuoted(spec.name))', :path => '\(rubySingleQuoted(spec.directoryPath))'"
            }
            return "  pod '\(rubySingleQuoted(spec.name))', '= \(rubySingleQuoted(spec.version))'"
        }.joined(separator: "\n")

        return """
        source 'https://cdn.cocoapods.org/'
        platform :ios, '12.0'
        project 'PackagingHost.xcodeproj'
        install! 'cocoapods', :deterministic_uuids => true
        use_frameworks! :linkage => :static

        target 'PackagingHost' do
        \(podLines)
        end
        """
    }

    // 写入一个最小 iOS App Xcode 工程，让 CocoaPods 生成可构建的 Workspace。
    private static func writeHostProject(
        at rootURL: URL,
        projectName: String,
        sourceFileName: String,
        sourceContents: String,
        sourceFileType: String,
        deploymentTarget: String
    ) throws {
        let sourceDirectory = rootURL.appendingPathComponent(projectName, isDirectory: true)
        let projectDirectory = rootURL.appendingPathComponent("\(projectName).xcodeproj", isDirectory: true)
        try FileManager.default.createDirectory(
            at: sourceDirectory,
            withIntermediateDirectories: true
        )
        try FileManager.default.createDirectory(
            at: projectDirectory,
            withIntermediateDirectories: true
        )
        try sourceContents.write(
            to: sourceDirectory.appendingPathComponent(sourceFileName),
            atomically: true,
            encoding: .utf8
        )
        try infoPlist(bundleName: projectName).write(
            to: sourceDirectory.appendingPathComponent("Info.plist"),
            atomically: true,
            encoding: .utf8
        )
        try projectPBXProj(
            projectName: projectName,
            sourceFileName: sourceFileName,
            sourceFileType: sourceFileType,
            deploymentTarget: deploymentTarget
        ).write(
            to: projectDirectory.appendingPathComponent("project.pbxproj"),
            atomically: true,
            encoding: .utf8
        )
    }

    // 生成最小 Xcode project.pbxproj。
    private static func projectPBXProj(
        projectName: String,
        sourceFileName: String,
        sourceFileType: String,
        deploymentTarget: String
    ) -> String {
        """
        // !$*UTF8*$!
        {
          archiveVersion = 1;
          classes = {
          };
          objectVersion = 56;
          objects = {

        /* Begin PBXBuildFile section */
            A10000000000000000000001 /* \(sourceFileName) in Sources */ = {isa = PBXBuildFile; fileRef = A10000000000000000000002 /* \(sourceFileName) */; };
        /* End PBXBuildFile section */

        /* Begin PBXFileReference section */
            A10000000000000000000002 /* \(sourceFileName) */ = {isa = PBXFileReference; lastKnownFileType = \(sourceFileType); path = \(sourceFileName); sourceTree = "<group>"; };
            A10000000000000000000003 /* \(projectName).app */ = {isa = PBXFileReference; explicitFileType = wrapper.application; includeInIndex = 0; path = \(projectName).app; sourceTree = BUILT_PRODUCTS_DIR; };
            A10000000000000000000004 /* Info.plist */ = {isa = PBXFileReference; lastKnownFileType = text.plist.xml; path = Info.plist; sourceTree = "<group>"; };
        /* End PBXFileReference section */

        /* Begin PBXFrameworksBuildPhase section */
            A10000000000000000000005 /* Frameworks */ = {
              isa = PBXFrameworksBuildPhase;
              buildActionMask = 2147483647;
              files = (
              );
              runOnlyForDeploymentPostprocessing = 0;
            };
        /* End PBXFrameworksBuildPhase section */

        /* Begin PBXGroup section */
            A10000000000000000000006 = {
              isa = PBXGroup;
              children = (
                A10000000000000000000007 /* \(projectName) */,
                A10000000000000000000008 /* Products */,
              );
              sourceTree = "<group>";
            };
            A10000000000000000000007 /* \(projectName) */ = {
              isa = PBXGroup;
              children = (
                A10000000000000000000002 /* \(sourceFileName) */,
                A10000000000000000000004 /* Info.plist */,
              );
              path = \(projectName);
              sourceTree = "<group>";
            };
            A10000000000000000000008 /* Products */ = {
              isa = PBXGroup;
              children = (
                A10000000000000000000003 /* \(projectName).app */,
              );
              name = Products;
              sourceTree = "<group>";
            };
        /* End PBXGroup section */

        /* Begin PBXNativeTarget section */
            A10000000000000000000009 /* \(projectName) */ = {
              isa = PBXNativeTarget;
              buildConfigurationList = A10000000000000000000010 /* Build configuration list for PBXNativeTarget "\(projectName)" */;
              buildPhases = (
                A10000000000000000000011 /* Sources */,
                A10000000000000000000005 /* Frameworks */,
                A10000000000000000000012 /* Resources */,
              );
              buildRules = (
              );
              dependencies = (
              );
              name = \(projectName);
              productName = \(projectName);
              productReference = A10000000000000000000003 /* \(projectName).app */;
              productType = "com.apple.product-type.application";
            };
        /* End PBXNativeTarget section */

        /* Begin PBXProject section */
            A10000000000000000000013 /* Project object */ = {
              isa = PBXProject;
              attributes = {
                BuildIndependentTargetsInParallel = 1;
                LastSwiftUpdateCheck = 1600;
                LastUpgradeCheck = 1600;
                TargetAttributes = {
                  A10000000000000000000009 = {
                    CreatedOnToolsVersion = 16.0;
                  };
                };
              };
              buildConfigurationList = A10000000000000000000014 /* Build configuration list for PBXProject "\(projectName)" */;
              compatibilityVersion = "Xcode 14.0";
              developmentRegion = en;
              hasScannedForEncodings = 0;
              knownRegions = (
                en,
                Base,
              );
              mainGroup = A10000000000000000000006;
              productRefGroup = A10000000000000000000008 /* Products */;
              projectDirPath = "";
              projectRoot = "";
              targets = (
                A10000000000000000000009 /* \(projectName) */,
              );
            };
        /* End PBXProject section */

        /* Begin PBXResourcesBuildPhase section */
            A10000000000000000000012 /* Resources */ = {
              isa = PBXResourcesBuildPhase;
              buildActionMask = 2147483647;
              files = (
              );
              runOnlyForDeploymentPostprocessing = 0;
            };
        /* End PBXResourcesBuildPhase section */

        /* Begin PBXSourcesBuildPhase section */
            A10000000000000000000011 /* Sources */ = {
              isa = PBXSourcesBuildPhase;
              buildActionMask = 2147483647;
              files = (
                A10000000000000000000001 /* \(sourceFileName) in Sources */,
              );
              runOnlyForDeploymentPostprocessing = 0;
            };
        /* End PBXSourcesBuildPhase section */

        /* Begin XCBuildConfiguration section */
            A10000000000000000000015 /* Debug */ = {
              isa = XCBuildConfiguration;
              buildSettings = {
                ALWAYS_SEARCH_USER_PATHS = NO;
                CLANG_ENABLE_MODULES = YES;
                IPHONEOS_DEPLOYMENT_TARGET = \(deploymentTarget);
                SDKROOT = iphoneos;
                SWIFT_VERSION = 5.0;
              };
              name = Debug;
            };
            A10000000000000000000016 /* Release */ = {
              isa = XCBuildConfiguration;
              buildSettings = {
                ALWAYS_SEARCH_USER_PATHS = NO;
                CLANG_ENABLE_MODULES = YES;
                IPHONEOS_DEPLOYMENT_TARGET = \(deploymentTarget);
                SDKROOT = iphoneos;
                SWIFT_COMPILATION_MODE = wholemodule;
                SWIFT_VERSION = 5.0;
              };
              name = Release;
            };
            A10000000000000000000017 /* Debug */ = {
              isa = XCBuildConfiguration;
              buildSettings = {
                CODE_SIGN_STYLE = Automatic;
                GENERATE_INFOPLIST_FILE = NO;
                INFOPLIST_FILE = \(projectName)/Info.plist;
                IPHONEOS_DEPLOYMENT_TARGET = \(deploymentTarget);
                LD_RUNPATH_SEARCH_PATHS = (
                  "$(inherited)",
                  "@executable_path/Frameworks",
                );
                PRODUCT_BUNDLE_IDENTIFIER = com.jobs.podbinarybuilder.\(projectName.lowercased());
                PRODUCT_NAME = "$(TARGET_NAME)";
                SWIFT_VERSION = 5.0;
                TARGETED_DEVICE_FAMILY = "1,2";
              };
              name = Debug;
            };
            A10000000000000000000018 /* Release */ = {
              isa = XCBuildConfiguration;
              buildSettings = {
                CODE_SIGN_STYLE = Automatic;
                GENERATE_INFOPLIST_FILE = NO;
                INFOPLIST_FILE = \(projectName)/Info.plist;
                IPHONEOS_DEPLOYMENT_TARGET = \(deploymentTarget);
                LD_RUNPATH_SEARCH_PATHS = (
                  "$(inherited)",
                  "@executable_path/Frameworks",
                );
                PRODUCT_BUNDLE_IDENTIFIER = com.jobs.podbinarybuilder.\(projectName.lowercased());
                PRODUCT_NAME = "$(TARGET_NAME)";
                SWIFT_VERSION = 5.0;
                TARGETED_DEVICE_FAMILY = "1,2";
              };
              name = Release;
            };
        /* End XCBuildConfiguration section */

        /* Begin XCConfigurationList section */
            A10000000000000000000010 /* Build configuration list for PBXNativeTarget "\(projectName)" */ = {
              isa = XCConfigurationList;
              buildConfigurations = (
                A10000000000000000000017 /* Debug */,
                A10000000000000000000018 /* Release */,
              );
              defaultConfigurationIsVisible = 0;
              defaultConfigurationName = Release;
            };
            A10000000000000000000014 /* Build configuration list for PBXProject "\(projectName)" */ = {
              isa = XCConfigurationList;
              buildConfigurations = (
                A10000000000000000000015 /* Debug */,
                A10000000000000000000016 /* Release */,
              );
              defaultConfigurationIsVisible = 0;
              defaultConfigurationName = Release;
            };
        /* End XCConfigurationList section */
          };
          rootObject = A10000000000000000000013 /* Project object */;
        }
        """
    }

    // 生成临时宿主工程 Info.plist。
    private static func infoPlist(bundleName: String) -> String {
        """
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <dict>
          <key>CFBundleDevelopmentRegion</key>
          <string>$(DEVELOPMENT_LANGUAGE)</string>
          <key>CFBundleExecutable</key>
          <string>$(EXECUTABLE_NAME)</string>
          <key>CFBundleIdentifier</key>
          <string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
          <key>CFBundleInfoDictionaryVersion</key>
          <string>6.0</string>
          <key>CFBundleName</key>
          <string>\(bundleName)</string>
          <key>CFBundlePackageType</key>
          <string>$(PRODUCT_BUNDLE_PACKAGE_TYPE)</string>
          <key>CFBundleShortVersionString</key>
          <string>1.0</string>
          <key>CFBundleVersion</key>
          <string>1</string>
          <key>LSRequiresIPhoneOS</key>
          <true/>
          <key>UILaunchScreen</key>
          <dict/>
        </dict>
        </plist>
        """
    }

    // 计算从消费工程到二进制 SDK 根目录的相对路径。
    private static func relativePath(from baseURL: URL, to targetURL: URL) -> String {
        let baseComponents = baseURL.standardizedFileURL.pathComponents
        let targetComponents = targetURL.standardizedFileURL.pathComponents
        var sharedCount = 0
        while sharedCount < min(baseComponents.count, targetComponents.count),
              baseComponents[sharedCount] == targetComponents[sharedCount] {
            sharedCount += 1
        }
        let ups = Array(repeating: "..", count: baseComponents.count - sharedCount)
        let downs = Array(targetComponents.dropFirst(sharedCount))
        return (ups + downs).joined(separator: "/")
    }

    // 转义 Ruby 单引号字符串。
    private static func rubySingleQuoted(_ value: String) -> String {
        value
            .replacingOccurrences(of: "\\", with: "\\\\")
            .replacingOccurrences(of: "'", with: "\\'")
    }

    // 把字符串数组转换为 Ruby 数组字面量。
    private static func rubyArray(_ values: [String]) -> String {
        "[\(values.map { "'\(rubySingleQuoted($0))'" }.joined(separator: ", "))]"
    }

    private static let swiftHostSource = """
    import UIKit

    @main
    final class AppDelegate: UIResponder, UIApplicationDelegate {
        var window: UIWindow?

        func application(
            _ application: UIApplication,
            didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]? = nil
        ) -> Bool {
            let window = UIWindow(frame: UIScreen.main.bounds)
            window.rootViewController = UIViewController()
            window.makeKeyAndVisible()
            self.window = window
            return true
        }
    }
    """
}
